name: Builds uproot+ROOT images
on:
  push:

env:
  ROOTVER: 6.36.04
  UPROOTVER: 5.6.7

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push uproot+ROOT
        uses: docker/build-push-action@v3
        with:
          context: combined_root
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            ROOTVER=${{ env.ROOTVER }}
            UPROOTVER=${{ env.UPROOTVER }}
          tags: sslhep/servicex_science_image_combined_root:${{ env.UPROOTVER }}-${{ env.ROOTVER }}
          platforms: linux/amd64,linux/arm64
